---
- src: https://github.com/wilmardo/ansible-role-plexupdate.git
  version: master
  name: plexupdate

- src: https://github.com/wilmardo/ansible-role-tautulli.git
  version: master
  name: tautulli
