---
- name: Install Yum on Fedora
  ansible.builtin.dnf:
    name: yum
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install Plex for Redhat family.
  when: ansible_os_family == "RedHat"
  block:
    - name: Add Plex Yum repo
      ansible.builtin.yum_repository:
        name: plex
        description: Plex Yum Repository
        baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
        gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key
        gpgcheck: true

    - name: Yum install Plex
      ansible.builtin.yum:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

- name: Install Plex for Debian family.
  when: ansible_os_family == "Debian"
  block:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    # based on https://stackoverflow.com/a/71384057
    # TODO: update to newer DEB822 format in 2024
    - name: Add Plex apt key (Debian).
      ansible.builtin.get_url:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        dest: /etc/apt/keyrings/plex.asc
        mode: '0644'

    - name: Add Plex apt repo (Debian).
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/plex.asc] https://downloads.plex.tv/repo/deb public main"
        state: present

    - name: Apt install Plex
      ansible.builtin.apt:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

- name: Allow Plex to local network.
  block:
    - name: Copy Plex UFW configuration to server.
      ansible.builtin.copy:
        src: files/plexmediaserver
        dest: /etc/ufw/applications.d/plexmediaserver
        mode: '0644'

    - name: Apply Plex rules to UFW via profile in /etc/ufw/applications.d/.
      community.general.ufw:
        rule: allow
        name: plexmediaserver-all
        state: reloaded

- name: Autostart Plex and start service
  ansible.builtin.service:
    name: plexmediaserver
    enabled: true
  notify: restart plex

- name: Add Plex user to media group.
  ansible.builtin.user:
    name: plex
    groups: [media]
    append: true
