---
- name: Install Yum on Fedora
  dnf:
    name: yum
    state: present
  when: ansible_distribution == 'Fedora'

- block:
    - name: Add Plex Yum repo
      yum_repository:
        name: plex
        description: Plex Yum Repository
        baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
        gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key
        gpgcheck: true

    - name: Yum install Plex
      yum:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

  when: ansible_os_family == "RedHat"

- block:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    # based on https://stackoverflow.com/a/71384057
    # TODO: update to newer DEB822 format in 2024
    - name: Add Plex apt key (Debian).
      ansible.builtin.get_url:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        dest: /etc/apt/keyrings/plex.asc

    - name: Add Plex apt repo (Debian).
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/plex.asc] https://downloads.plex.tv/repo/deb public main"
        state: present

    - name: Apt install Plex
      apt:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

  when: ansible_os_family == "Debian"

- name: Autostart Plex and start service
  service:
    name: plexmediaserver
    enabled: true
  notify: restart plex
