---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: Centos7
    image: lansible/centos:7

  - name: Centos6
    image: centos:6
    ulimits:
      - memlock:60397977:60397977

  - name: Debian9
    image: lansible/debian:8

  - name: Fedora27
    image: lansible/fedora:27

  - name: Fedora26
    image: lansible/fedora:26

  - name: Fedora25
    image: lansible/fedora:25

  - name: Ubuntu1604
    image: lansible/ubuntu:16.04

#  - name: Ubuntu1404
#    image: lansible/ubuntu:14.04

provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

scenario:
  name: default
