---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: Plex-Centos7
    image: lansible/centos:7

#  - name: Plex-Centos6
#    image: lansible/centos:6

  - name: Plex-Debian9
    image: lansible/debian:9

  - name: Plex-Debian8
    image: lansible/debian:8

#  - name: Plex-Fedora27
#    image: lansible/fedora:27
#
#  - name: Plex-Fedora26
#    image: lansible/fedora:26
#
#  - name: Plex-Fedora25
#    image: lansible/fedora:25

  - name: Plex-Ubuntu1604
    image: lansible/ubuntu:16.04

#  - name: Plex-Ubuntu1404
#    image: lansible/ubuntu:14.04

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

scenario:
  name: default
